services:
  freeradius:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: freeradius-entra-id
    build: .
    ports:
      - "1812-1813:1812-1813/udp"
    command: freeradius -X

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: freeradius
      POSTGRES_PASSWORD: pass
    # Check that PostgreSQL is up before considering container to be ready.
    # Based on https://github.com/peter-evans/docker-compose-healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./config/postgresql/create-database.sh:/docker-entrypoint-initdb.d/create-database.sh:ro

  # It's also possible to set up a highly-available cluster of Redis nodes,
  # see https://www.merge.dev/blog/how-to-spin-up-redis-cluster-in-docker
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./config/redis/redis.conf:/etc/redis/redis.conf:ro
    command: ["redis-server", "/etc/redis/redis.conf"]
